version: '3.11'

services:

  api:
    image: beatrizrodriguesf/api-image:latest
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-projeto}
      POSTGRES_USER: ${POSTGRES_USER:-projeto}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-projeto}
    expose:
      - 5432